apiVersion: apps/v1
kind: Deployment
metadata:
  name:
    $patch: prefix
    value: gibbon-
  namespace: mynamespace
spec:
  selector:
    matchLabels:
      app: gibbon-traffic-manager
      telepresence: manager
  template:
    metadata:
      labels:
        app: gibbon-traffic-manager
        engine:
          $patch: prefix
          value: gibbon-
        telepresence: manager
        engine/version:
          $patch: prefix
          value: gibbon-0.0.1
    spec:
      containers:
      - name: gibbon-traffic-manager
        env:
        - name: AGENT_MOUNT_POLICIES
          value:
            '"/tmp"': '"Local"'
        - name: NOT_USED_NSS
          value:
            name: NOT_USED_NSS
            value: '["kube-system","kube-node-lease"]'
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts: []
        workingDir: /app
      serviceAccount:
        $patch: prefix
        value: gibbon-
      serviceAccountName:
        $patch: prefix
        value: gibbon-
