apiVersion: apps/v1
kind: Deployment
metadata:
  name:
    name: gibbon-gibbon-traffic-manager
  namespace: mynamespace
  labels:
    engine:
      engine: gibbon
    engine/version:
      engine/version: 0.0.1
spec:
  selector:
    matchLabels:
      app:
        app: gibbon-gibbon-traffic-manager
      telepresence: manager
  template:
    metadata:
      labels:
        app:
          app: gibbon-gibbon-traffic-manager
        engine: gibbon
        telepresence: manager
        engine/version: 0.0.1
    spec:
      containers:
      - name:
          name: gibbon-gibbon-traffic-manager
        env:
        - name: AGENT_MOUNT_POLICIES
          value:
            AGENT_MOUNT_POLICIES:
              /tmp: Local
        - name: NOT_USED_NSS
          value:
            kube-system","kube-node-lease: NOT_USED_NSS
            value: '["kube-system","kube-node-lease"]'
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts: []
        workingDir: /app
      serviceAccount:
        serviceAccount: gibbon-gibbon-traffic-manager
      serviceAccountName:
        serviceAccountName: gibbon-gibbon-traffic-manager
