apiVersion: v1
kind: Secret
metadata:
  name:
    name: gibbon-gibbon-mutator-webhook-tls
  namespace: mynamespace
  labels:
    engine/value:
      name: gibbon-gibbon-mutator-webhook-tls
  annotations:
    engine/value:
      AGENT_MOUNT_POLICIES: /tmp":"Local
      NOT_USED_NSS:
        name: kube-system,kube-node-lease
type: Opaque
