apiVersion: v1
kind: Secret
metadata:
  name:
    name: gibbon-mutator-webhook-tls
    namespace: mynamespace
  namespace: mynamespace
  labels:
    gibbon/name:
      name: gibbon-mutator-webhook-tls
      namespace: mynamespace
    engine:
      name: gibbon-mutator-webhook-tls
      namespace: mynamespace
    engine/version:
      name: gibbon-mutator-webhook-tls
      namespace: mynamespace
type: Opaque
