apiVersion: v1
kind: ServiceAccount
metadata:
  name:
    name: gibbon-gibbon-traffic-manager
  namespace: mynamespace
  labels:
    engine:
      name: gibbon
    engine/version:
      name: 0.0.1
secrets:
- name:
    name: gibbon-gibbon-traffic-manager-token-<token>
