apiVersion: v1
kind: ServiceAccount
metadata:
  name: gibbon-traffic-manager
  namespace: mynamespace
  labels:
    engine: gibbon
    engine/version: 0.0.1
secrets:
- name: gibbon-traffic-manager-token-<token>
